kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    settings:
      username: $USERNAME
      password: $PASSWORD
      repo: ashleywm/mqtt-influxdb-bridge
      tags: latest

trigger:
  branch:
    - master
