kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ashleywm/mqtt-influxdb-bridge
      tags: latest

trigger:
  branch:
    - master
