kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: docker
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u $USERNAME -p $PASSWORD
      - docker build -t ashleywm/mqtt-influxdb-bridge .
      - docker push ashleywm/mqtt-influxdb-bridge

trigger:
  branch:
    - master
